### ISSUE TITLE
Bug on blackjack embed.

### ISSUE THREAD

**Issue by du-cki** [Kagetasu/KnaiPy#2]
Hey, I made this GitHub Issue to point out there is a crucial spelling error in your blackjack command. As you can see here;

![image](https://github.com/Kagetasu/KnaiPy/assets/70286349/7d51403d-eeb7-4d7c-9f20-9e75e3e1e18e)

On the first field, the `:` is present but on the second field it is nowhere to be found.

I hope this issue finds you well.

Cheers!

**Comment by Kagetasu** [comment]
Oh apologies, this will be fixed in the next commit.

Thank you for pointing it out
